---
include:
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: nice_view
    cmake-args: -DKEYMAP_FILE=${GITHUB_WORKSPACE}/boards/arm/eyelash_corne/eyelash_sofle.keymap '-DCONFIG_ZMK_KEYBOARD_NAME="Eyelash Sofle"'
    artifact-name: eyelash_sofle_left
  - board: eyelash_corne_right
    shield: nice_view
    cmake-args: -DKEYMAP_FILE=${GITHUB_WORKSPACE}/boards/arm/eyelash_corne/eyelash_sofle.keymap
    artifact-name: eyelash_sofle_right
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
