name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "boards/arm/eyelash_corne/**"
      - .github/workflows/draw.yml
      - keymap_drawer.config.yaml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      amend_commit: true
      destination: commit
      draw_args: "eyelash_corne:'-d boards/arm/eyelash_corne/eyelash_corne-layouts.dtsi -l corne_layout' eyelash_sofle:'-d boards/arm/eyelash_corne/eyelash_corne-layouts.dtsi -l sofle_layout'"
      fail_on_error: ${{ fromJSON(true) }}
      keymap_patterns: "boards/arm/eyelash_corne/*.keymap"
